### ISSUE TITLE
`nord-16 is not a valid colorscheme`

### ISSUE THREAD

**Issue by luciofstars** [KiranWells/micro-nord-tc-colors#7]
I get this in the terminal after setting the `nord-16` color theme as instructed in the README:

![image](https://github.com/user-attachments/assets/835bef7f-540c-48b1-8824-328aa0ab70eb)

**Comment by AntonFriberg** [comment]
Same issue for me.

**Comment by luciofstars** [comment]
Solved in #2 mb
